---
- name: Install the Nginx Repository 
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
 
- name: Install Nginx
  apt:
    name: nginx
    state: installed
    update_cache: yes

- name: Copy the templates to their respestive destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}" 
  with_items:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'virtualhost.conf.j2', dest: '/etc/nginx/sites-available/{{ server_name }}' }
    - { src: 'index.php.j2', dest: '/var/www/html/index.php', owner: 'www-data', group: 'www-data' }
  notify:
    - Restart Nginx

- name: Perform action of the desired files
  file:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: '/etc/nginx/sites-enabled/default', state: 'absent' }
    - { dest: '/var/www/html/index.nginx-debian.html', state: 'absent' }
    - { src: '/etc/nginx/sites-available/{{ server_name }}', dest: '/etc/nginx/sites-enabled/{{ server_name }}', state: 'link' }
  notify:
    - Restart Nginx